import os
import io
import datetime
from typing import List, Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
)
from reportlab.lib import colors
from reportlab.pdfgen import canvas

# Import custom styling and charts
from app.report.pdf.styles import (
    get_report_styles, ACCENT_COLOR, PRIMARY_COLOR, SECONDARY_COLOR,
    MUTED_COLOR, BORDER_COLOR, BG_LIGHT, WHITE,
    GREEN_BG, GREEN_TEXT, AMBER_BG, AMBER_TEXT, RED_BG, RED_TEXT
)
from app.report.pdf.charts import (
    draw_pilo_mascot, create_gauge_chart, create_progress_bar,
    create_skills_distribution_chart, create_difficulty_chart
)
from app.report.report_models import CareerReport

class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to calculate total page count and draw running headers and footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_header_footer(num_pages)
            super().showPage()
        super().save()

    def draw_header_footer(self, page_count):
        if self._pageNumber == 1:
            return  # Suppress headers/footers on the cover page
            
        self.saveState()
        
        # 1. Header
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(ACCENT_COLOR)
        self.drawString(54, 750, "ResumePilot AI")
        self.setFont("Helvetica", 8)
        self.setFillColor(SECONDARY_COLOR)
        self.drawRightString(558, 750, "Career Intelligence Report")
        
        # Header line
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # 2. Footer
        self.line(54, 52, 558, 52)
        self.drawString(54, 40, "ResumePilot AI  |  Generated by LangGraph Multi-Agent System  |  Powered by Groq + ChromaDB")
        self.drawRightString(558, 40, f"Page {self._pageNumber} of {page_count}")
        
        self.restoreState()

class PDFGenerator:
    @staticmethod
    def generate(report: CareerReport) -> bytes:
        """Transforms a CareerReport object into a premium, vector-based PDF."""
        buffer = io.BytesIO()
        
        # Setup document properties
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=64,
            bottomMargin=64
        )
        
        styles = get_report_styles()
        story = []
        
        # ----------------------------------------------------
        # 1. COVER PAGE
        # ----------------------------------------------------
        story.append(Spacer(1, 40))
        
        # Logo + Mascot Block
        logo_table = Table(
            [[draw_pilo_mascot(70), Paragraph("ResumePilot<font color='#5B5FEF'>.ai</font>", styles["CoverTitle"])]],
            colWidths=[80, 424]
        )
        logo_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (1, 0), (1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
        ]))
        story.append(logo_table)
        
        story.append(Paragraph("AI-Powered Resume Intelligence Report", styles["CoverSubtitle"]))
        story.append(Spacer(1, 30))
        
        # Candidate and Metadata Info
        meta_html = f"""
        <b>Candidate:</b> {report.candidate_info.name}<br/>
        <b>Target Role:</b> {report.target_role}<br/>
        <b>Generated Date:</b> {datetime.datetime.strptime(report.generated_timestamp[:10], "%Y-%m-%d").strftime("%B %d, %Y") if report.generated_timestamp else "N/A"}<br/>
        <b>Report Version:</b> {report.report_version}
        """
        story.append(Paragraph(meta_html, styles["CoverMeta"]))
        story.append(Spacer(1, 50))
        
        # Gauge Charts side-by-side on Cover Page
        gauge_story = []
        gauge1 = create_gauge_chart(report.overall_score, "Overall Score")
        gauge2 = create_gauge_chart(report.ats_score, "ATS Score")
        
        has_job_match = report.job_match_score is not None
        if has_job_match:
            gauge3 = create_gauge_chart(report.job_match_score, "Job Match Score")
            col_widths = [168, 168, 168]
            cols = [gauge1, gauge2, gauge3]
        else:
            col_widths = [252, 252]
            cols = [gauge1, gauge2]
            
        gauges_table = Table([cols], colWidths=col_widths)
        gauges_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(gauges_table)
        story.append(Spacer(1, 20))
        
        # Branding notice at cover page bottom
        desc_box = Table(
            [[Paragraph("This report provides deep, vector-guided career path and resume assessments generated via real-time multi-agent supervisor auditing and ChromaDB knowledge bases. Verify suggestions before deployment.", styles["ReportBodyMuted"])]],
            colWidths=[504]
        )
        desc_box.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BG_LIGHT),
            ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ]))
        story.append(desc_box)
        
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 2. EXECUTIVE SUMMARY
        # ----------------------------------------------------
        story.append(Paragraph("Executive Summary", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        
        summary_intro = """
        This career readiness document is composed by professional AI recruiter agents. Below is the executive consolidation of your current resume assets, ATS metrics, and career pathway roadmap.
        """
        story.append(Paragraph(summary_intro, styles["ReportBody"]))
        story.append(Spacer(1, 8))
        
        # Overview Cards Table
        overview_data = [
            [
                Paragraph("<b>Resume Quality</b>", styles["CardTitle"]),
                Paragraph("<b>ATS Compatibility</b>", styles["CardTitle"]),
                Paragraph("<b>Career Readiness</b>", styles["CardTitle"])
            ],
            [
                Paragraph(f"Score: {report.overall_score}/100<br/>The document shows solid baseline details.", styles["ReportBodyMuted"]),
                Paragraph(f"ATS Index: {report.ats_score}%<br/>Structure and keywords have been parsed.", styles["ReportBodyMuted"]),
                Paragraph(f"Match: {f'{report.job_match_score}%' if has_job_match else 'N/A'}<br/>Bridge the skill gaps to meet requirements.", styles["ReportBodyMuted"])
            ]
        ]
        overview_table = Table(overview_data, colWidths=[168, 168, 168])
        overview_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BG_LIGHT),
            ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ]))
        story.append(overview_table)
        story.append(Spacer(1, 15))
        
        # Strengths & Weaknesses side-by-side
        sw_data = [
            [Paragraph("<b>Key Strengths</b>", styles["CardTitle"]), Paragraph("<b>Areas for Improvement</b>", styles["CardTitle"])],
            [
                Paragraph("".join([f"• {s}<br/>" for s in report.strengths]) if report.strengths else "No strengths compiled.", styles["ReportBody"]),
                Paragraph("".join([f"• {w}<br/>" for w in report.weaknesses]) if report.weaknesses else "No weaknesses compiled.", styles["ReportBody"])
            ]
        ]
        sw_table = Table(sw_data, colWidths=[246, 246])
        sw_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (0, -1), 12),
            ('LEFTPADDING', (1, 0), (1, -1), 12),
        ]))
        story.append(sw_table)
        story.append(Spacer(1, 15))
        
        # Overall Recommendation (Highlighted Card)
        overall_rec = f"""
        <b>Overall Recommendation:</b> Based on your target role of <b>{report.target_role}</b>, we recommend completing the {len(report.project_recommendations)} recommended hands-on projects, resolving high-priority phrasing improvements, and adding missing technologies to raise your match index.
        """
        rec_box = Table([[Paragraph(overall_rec, styles["ReportBody"])]], colWidths=[504])
        rec_box.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BG_LIGHT),
            ('BOX', (0, 0), (-1, -1), 1.0, ACCENT_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('LEFTPADDING', (0, 0), (-1, -1), 14),
            ('RIGHTPADDING', (0, 0), (-1, -1), 14),
        ]))
        story.append(rec_box)
        
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 3. RESUME ANALYSIS (ATS Checklist)
        # ----------------------------------------------------
        story.append(Paragraph("Resume Formatting & Layout Audit", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph("Our ATS Analyst audited standard format blocks, verb density, layout structures, and spelling rules:", styles["ReportBody"]))
        story.append(Spacer(1, 8))
        
        # Create a detailed table for ATS Checklist
        checklist_rows = []
        for item in report.ats_analysis:
            status = item.get("status", "pass").lower()
            if status == "pass":
                status_html = "<font color='#137333'><b>✔ PASS</b></font>"
                bg_col = GREEN_BG
            elif status == "warn":
                status_html = "<font color='#B06000'><b>⚠ WARN</b></font>"
                bg_col = AMBER_BG
            else:
                status_html = "<font color='#C5221F'><b>✘ FAIL</b></font>"
                bg_col = RED_BG
                
            checklist_rows.append([
                Paragraph(f"<b>{item.get('title', 'Metric')}</b>", styles["TableCellBold"]),
                Paragraph(item.get("desc", ""), styles["TableCell"]),
                Paragraph(status_html, styles["BadgeText"])
            ])
            
        checklist_table = Table(checklist_rows, colWidths=[150, 274, 80])
        checklist_table.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ('ROWBACKGROUNDS', (0, 0), (-1, -1), [WHITE, BG_LIGHT])
        ]))
        story.append(checklist_table)
        
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 4. JOB MATCH ANALYSIS
        # ----------------------------------------------------
        story.append(Paragraph("Job Description Matching", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        
        if not report.job_match_analysis:
            story.append(Paragraph("<i>No Job Description was provided for matching analysis. Upload a specific Job Description to generate detailed compatibility reports, matching keywords, and alignment scores.</i>", styles["ReportBody"]))
        else:
            match_data = report.job_match_analysis
            intro_match = f"Compatibility comparison against job description for: <b>{match_data.get('role', report.target_role)}</b> at <b>{match_data.get('company_name', 'Target Company')}</b>."
            story.append(Paragraph(intro_match, styles["ReportBody"]))
            story.append(Spacer(1, 8))
            
            # Progress bars table
            pb_table_data = [
                [
                    Paragraph("<b>Overall Match Index</b>", styles["TableCellBold"]),
                    create_progress_bar(match_data.get("overall_match_score", 50), width=150, color="#5B5FEF"),
                    Paragraph(f"<b>{match_data.get('overall_match_score', 50)}%</b>", styles["TableCellBold"])
                ],
                [
                    Paragraph("<b>ATS Match Percentage</b>", styles["TableCellBold"]),
                    create_progress_bar(match_data.get("ats_match_percentage", 50), width=150, color="#10B981"),
                    Paragraph(f"<b>{match_data.get('ats_match_percentage', 50)}%</b>", styles["TableCellBold"])
                ]
            ]
            pb_table = Table(pb_table_data, colWidths=[150, 200, 154])
            pb_table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ]))
            story.append(pb_table)
            story.append(Spacer(1, 10))
            
            # Detailed Matches Table
            details_rows = [
                [Paragraph("<b>Evaluation Category</b>", styles["TableHeader"]), Paragraph("<b>Alignment Status</b>", styles["TableHeader"])],
                [Paragraph("Experience Compatibility", styles["TableCellBold"]), Paragraph(match_data.get("experience_match", "N/A"), styles["TableCell"])],
                [Paragraph("Education Credentials", styles["TableCellBold"]), Paragraph(match_data.get("education_match", "N/A"), styles["TableCell"])],
                [Paragraph("Certifications Requested", styles["TableCellBold"]), Paragraph(match_data.get("certification_match", "N/A"), styles["TableCell"])],
            ]
            details_table = Table(details_rows, colWidths=[180, 324])
            details_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), ACCENT_COLOR),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ('TOPPADDING', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
                ('LEFTPADDING', (0, 0), (-1, -1), 10),
                ('RIGHTPADDING', (0, 0), (-1, -1), 10),
            ]))
            story.append(details_table)
            story.append(Spacer(1, 15))
            
            # Match/Gaps details
            skills_cols = [
                [
                    Paragraph("<b>Matched Competencies</b>", styles["CardTitle"]),
                    Paragraph(", ".join(match_data.get("matched_skills", [])) if match_data.get("matched_skills") else "None detected.", styles["ReportBody"])
                ],
                [
                    Paragraph("<b>Missing Keywords</b>", styles["CardTitle"]),
                    Paragraph(", ".join(match_data.get("missing_keywords", [])) if match_data.get("missing_keywords") else "None detected.", styles["ReportBody"])
                ]
            ]
            skills_table = Table([skills_cols], colWidths=[252, 252])
            skills_table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('RIGHTPADDING', (0, 0), (0, -1), 10),
                ('LEFTPADDING', (1, 0), (1, -1), 10),
            ]))
            story.append(skills_table)
            
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 5. SKILLS ANALYSIS
        # ----------------------------------------------------
        story.append(Paragraph("Skills Analysis", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph("A comparison of identified assets vs. target role demands. Below is the vector skills breakdown:", styles["ReportBody"]))
        story.append(Spacer(1, 10))
        
        # Skills block details
        skills_layout_data = [
            [
                Paragraph("<b>Current Skills</b>", styles["CardTitle"]),
                Paragraph(", ".join(report.skills_analysis) if report.skills_analysis else "None parsed.", styles["ReportBody"])
            ],
            [
                Paragraph("<b>Missing Skills (High Priority)</b>", styles["CardTitle"]),
                Paragraph(", ".join(report.missing_skills) if report.missing_skills else "None identified.", styles["ReportBody"])
            ]
        ]
        skills_layout_table = Table(skills_layout_data, colWidths=[150, 354])
        skills_layout_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BACKGROUND', (0, 0), (0, -1), BG_LIGHT),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(skills_layout_table)
        story.append(Spacer(1, 20))
        
        # Embed Skills distribution chart
        chart_group = []
        matching_cnt = len(report.skills_analysis)
        missing_cnt = len(report.missing_skills)
        chart_group.append(create_skills_distribution_chart(matching_cnt, missing_cnt))
        
        chart_table = Table([chart_group], colWidths=[504])
        chart_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10)
        ]))
        story.append(chart_table)
        
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 6. PROJECT RECOMMENDATIONS
        # ----------------------------------------------------
        story.append(Paragraph("Target Project Recommendations", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph("Complete these hands-on projects to bridge identified skill gaps and add metric-driven achievements to your profile:", styles["ReportBody"]))
        story.append(Spacer(1, 10))
        
        # Render project cards
        easy_cnt, med_cnt, hard_cnt = 0, 0, 0
        for idx, proj in enumerate(report.project_recommendations):
            diff = proj.get("difficulty", "Medium")
            if diff.lower() == "easy":
                easy_cnt += 1
            elif diff.lower() == "hard":
                hard_cnt += 1
            else:
                med_cnt += 1
                
            proj_html = f"""
            <b>{idx + 1}. {proj.get('title', 'Recommended Project')}</b><br/>
            <i>Difficulty: {diff} | Est. Duration: {proj.get('duration', 'N/A')}</i><br/>
            {proj.get('description', '')}<br/><br/>
            <b>Skills Gained:</b> {", ".join(proj.get('skills_learned', []))}<br/>
            <b>Resume Impact:</b> {proj.get('resume_impact', {}).get('value_description') if isinstance(proj.get('resume_impact'), dict) else 'Highly valued credential.'}<br/>
            <b>Outcome:</b> {proj.get('learning_outcome', 'Complete product deployment.')}
            """
            
            proj_card = Table([[Paragraph(proj_html, styles["ReportBody"])]], colWidths=[504])
            proj_card.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, -1), BG_LIGHT),
                ('BOX', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ('TOPPADDING', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
                ('LEFTPADDING', (0, 0), (-1, -1), 12),
                ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ]))
            story.append(proj_card)
            story.append(Spacer(1, 10))
            
        # Draw Project Difficulty Breakdown Chart
        story.append(Spacer(1, 15))
        diff_chart = create_difficulty_chart(easy_cnt, med_cnt, hard_cnt)
        diff_table = Table([[diff_chart]], colWidths=[504])
        diff_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ]))
        story.append(diff_table)
        
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 7. LEARNING ROADMAP
        # ----------------------------------------------------
        story.append(Paragraph("Learning Roadmap", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph("Follow this structured sequence to build capabilities and upgrade your resume index systematically:", styles["ReportBody"]))
        story.append(Spacer(1, 10))
        
        # Timeline represented as a table layout
        timeline_rows = []
        for step in report.learning_roadmap:
            step_num = step.get("step", 1)
            dur = step.get("duration", "N/A")
            topic = step.get("topic", "")
            desc = step.get("description", "Focus on practical projects and code deployments.")
            
            left_col = f"<b>Step {step_num}</b><br/><font color='#64748B'>{dur}</font>"
            right_col = f"<b>{topic}</b><br/>{desc}"
            
            timeline_rows.append([
                Paragraph(left_col, styles["TableCellBold"]),
                Paragraph(right_col, styles["TableCell"])
            ])
            
        timeline_table = Table(timeline_rows, colWidths=[100, 404])
        timeline_table.setStyle(TableStyle([
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BACKGROUND', (0, 0), (0, -1), BG_LIGHT),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ]))
        story.append(timeline_table)
        
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 8. RESUME REWRITE SUGGESTIONS
        # ----------------------------------------------------
        story.append(Paragraph("Resume Rewrite Suggestions", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph("Replace passive verbs and flat bullet statements with metric-driven, impact-oriented phrasing suggested by our AI Resume Architect:", styles["ReportBody"]))
        story.append(Spacer(1, 10))
        
        # Revisions Table
        revisions_rows = [
            [
                Paragraph("<b>Original Phrasing</b>", styles["TableHeader"]),
                Paragraph("<b>Suggested Rewrite</b>", styles["TableHeader"]),
                Paragraph("<b>Rationale</b>", styles["TableHeader"])
            ]
        ]
        
        for item in report.resume_rewrite_suggestions:
            revisions_rows.append([
                Paragraph(f"<i>\"{item.get('original', '')}\"</i>", styles["TableCell"]),
                Paragraph(f"<b>\"{item.get('improved', '')}\"</b>", styles["TableCellBold"]),
                Paragraph(item.get("rationale", ""), styles["TableCell"])
            ])
            
        revisions_table = Table(revisions_rows, colWidths=[150, 184, 170])
        revisions_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), ACCENT_COLOR),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [WHITE, BG_LIGHT])
        ]))
        story.append(revisions_table)
        
        story.append(PageBreak())
        
        # ----------------------------------------------------
        # 9. KNOWLEDGE SOURCES & FINAL AI RECOMMENDATION
        # ----------------------------------------------------
        story.append(Paragraph("RAG Knowledge References", styles["ReportH1"]))
        story.append(Spacer(1, 5))
        story.append(Paragraph("This assessment was cross-referenced and validated against standard professional templates and indexed guidebooks:", styles["ReportBody"]))
        story.append(Spacer(1, 8))
        
        sources_rows = [
            [Paragraph("<b>Document Guide</b>", styles["TableHeader"]), Paragraph("<b>Relevance Factor</b>", styles["TableHeader"])]
        ]
        for src in report.knowledge_sources_used:
            relevance = "High (Formatting & Phrasing Standards)" if "resume" in src.lower() else "Medium (Technical Skill Standards)"
            sources_rows.append([
                Paragraph(src.replace("_", " ").title(), styles["TableCellBold"]),
                Paragraph(relevance, styles["TableCell"])
            ])
            
        sources_table = Table(sources_rows, colWidths=[252, 252])
        sources_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), SECONDARY_COLOR),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(sources_table)
        story.append(Spacer(1, 30))
        
        # Final Highlight Block
        story.append(Paragraph("Final Career Recommendation", styles["ReportH2"]))
        story.append(Spacer(1, 5))
        
        final_text = f"""
        <b>Resume Readiness Level:</b> Medium Readiness<br/>
        <b>Potential Score Improvement:</b> +15 to +20 points after addressing phrasing revisions and skills gap projects.<br/><br/>
        <b>Key Takeaway:</b> Your profile demonstrates solid engineering principles. Focus on building and documenting projects in <b>{", ".join(report.missing_skills[:2]) if report.missing_skills else report.target_role}</b>. Update your experience bullets to include metrics, and configure automated releases.
        """
        
        final_box = Table([[Paragraph(final_text, styles["ReportBody"])]], colWidths=[504])
        final_box.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), BG_LIGHT),
            ('BOX', (0, 0), (-1, -1), 1.5, ACCENT_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('LEFTPADDING', (0, 0), (-1, -1), 14),
            ('RIGHTPADDING', (0, 0), (-1, -1), 14),
        ]))
        story.append(final_box)
        
        # Build Document
        doc.build(story, canvasmaker=NumberedCanvas)
        
        buffer.seek(0)
        return buffer.getvalue()
